//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEmpleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Anticipo = new HashSet<Anticipo>();
            this.Bonificacion_Empleado = new HashSet<Bonificacion_Empleado>();
            this.Permisos = new HashSet<Permisos>();
            this.Vacaciones = new HashSet<Vacaciones>();
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int Id_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Nro_Documento { get; set; }
        public string Tipo_Documento { get; set; }
        public string Direccion { get; set; }
        public string Nro_Telefono { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public Nullable<System.DateTime> Fecha_Incorporacion { get; set; }
        public string Imagen_Perfil { get; set; }
        public string Estado_Civil { get; set; }
        public int Salario_Basico { get; set; }
        public Nullable<int> Turno_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anticipo> Anticipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonificacion_Empleado> Bonificacion_Empleado { get; set; }
        public virtual Turno Turno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
