//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public int Id_Concepto { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }

        /*Tocamos solo para hacer cosas asi, nada de cambiar los tipos de datos autogenerados por el Entity framework...Ojo!*/
        public override string ToString()
        {
            return Descripcion;
        }

    }
}
