//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_Sistema
    {
        public int Id_Parametros { get; set; }
        public int Salario_Minimo_Vigente { get; set; }
        public string Mes_Anho_Salario_Minimo_Vigente { get; set; }
        public byte Porcentaje_Obrero_IPS { get; set; }
        public byte Porcentaje_Patronal_IPS { get; set; }
    }
}
