//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_Sistema
    {
        public int Id_Parametros { get; set; }
        public int Salario_Minimo_Vigente { get; set; }
        public string Mes_Anho_Salario_Minimo_Vigente { get; set; }
        public byte Porcentaje_Obrero_IPS { get; set; }
        public byte Porcentaje_Patronal_IPS { get; set; }
    }
}
